### ISSUE TITLE
500 Error when publishing Flake <autogenerated-issue>

### ISSUE THREAD

**Issue by xddxdd** [DeterminateSystems/flakehub-push#100]
## Error
```
Error: 
   0: Status 500 Internal Server Error from metadata POST
      "Internal server error"
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.0|
|**os**|linux|
|**arch**|x86_64|

## SpanTrace

<details>

```
SpanTrace:
   0: flakehub_push::cli::push_new_release
           with repository=xddxdd/nur-packages mirror=false upload_name=xddxdd/nur-packages source=/nix/store/25y52ywhf7030f0iz13ii2wpqbklz2rq-source
             at src/cli/mod.rs:472
   1: flakehub_push::cli::flakehub_push
             at src/cli/mod.rs:257
```
</details>

**Comment by cole-h** [comment]
Thanks for the issue! I suspect that this is related to using rolling releases: the way they work on FlakeHub is by setting the SemVer version's patch to the number of commits to the current branch.

This means if you were to force-push a new commit over an old commit that has already been released to FlakeHub, causing the number of commits on the branch to be the same for both the already-released version and the newly-force-pushed version, FlakeHub will reject this.

You can also reproduce this if you were to enable releasing from PRs and then squash-merge or rebase-merge those PRs in a way that causes the number of commits on the PR's branch (and thus the release that happened from that branch) to overlap with the number of commits on your main branch (and thus the release that wants to happen from the main branch).

I just deployed a change to FlakeHub that will give this situation a better error message so you will know what happened, rather than the opaque HTTP 500.

If you see this again, please feel free to re-open and I'll take another look!
